// Mostly generated by ChatGPT

import { useState } from 'react';

const avatars = [
  { id: 1, name: 'User 1', src: '/avatars/user1.jpg' },
  { id: 2, name: 'User 2', src: '/avatars/user2.jpg' },
  { id: 3, name: 'User 3', src: '/avatars/user3.jpg' },
  { id: 4, name: 'User 4', src: '/avatars/user4.jpg' },
];

type AvatarSelectorProps = {
  onClose: () => void;
};

export default function AvatarSelector({ onClose }: AvatarSelectorProps) {
  const [selectedAvatar, setSelectedAvatar] = useState<typeof avatars[0] | null>(null);

  const handleSelect = (avatar: typeof avatars[0]) => {
    setSelectedAvatar(avatar);
    onClose(); // Close the pop-up when an avatar is selected
  };

  return (
    <div className="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50">
      <div className="bg-white rounded-lg p-6 w-96">
        <h2 className="text-lg font-bold mb-4">Select an Avatar</h2>
        <div className="grid grid-cols-2 gap-4">
          {avatars.map((avatar) => (
            <div
              key={avatar.id}
              className={`cursor-pointer p-2 border rounded-lg ${selectedAvatar?.id === avatar.id ? 'border-blue-500' : 'border-gray-300'
                }`}
              onClick={() => handleSelect(avatar)}
            >
              <img src={avatar.src} alt={avatar.name} className="w-full h-20 object-cover rounded" />
              <p className="text-center mt-2">{avatar.name}</p>
            </div>
          ))}
        </div>
        <button
          onClick={onClose}
          className="mt-6 w-full bg-blue-500 text-white py-2 rounded-lg hover:bg-blue-600"
        >
          Close
        </button>
      </div>
    </div>
  );
}